name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create revision'
        required: true

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Windows Exe
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'main.py'
          upload_exe_with_name: 'RootDraftMakerWindows'
          options: --onefile, --name "RootDraftMaker", --windowed,
      - name: Upload content
        uses: actions/upload-artifact@v2
        with:
          name: Content
          path: ./content.json

  macos-build:
    runs-on: macos-13
    steps:
      - name: Mac Exe
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'main.py'
          upload_exe_with_name: 'RootDraftMakerMac'
          options: --onefile, --name "RootDraftMaker", --windowed,
  release:
    needs: [windows-build, macos-build]
    runs-on: ubuntu-latest
    steps:
      - name: Get Windows Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: RootDraftMakerWindows
      - name: Get Mac Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: RootDraftMakerMac
      - name: Get Content Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: Content
      - name: Print directory structure
        run: |
          ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            RootDraftMakerWindows.exe
            RootDraftMakerMac
            content.json
          tag_name: ${{ github.event.inputs.tag }}